#############################################################################################
# The paths to the input and output files and required parameters

## INPUT FILES

STUDENTS_LIST: "./students_data/Student List HSS Registration 2021-22.xlsx"
# path to the file containing the list of students who will pre register

STUDENT_COURSES: "./students_data/Student Wise Courses HSS Registration 2021-22.xlsx"
# path to the file containing the unique codes shared to the students for authentication

STUDENT_FORM_DATA: "./students_data/HSS Pre-registration 2021-22.xlsx"
# path to the file containing the students data collected through form

COURSE_DATA: "./pre_registration_data/List of HSS Courses with Caps.xlsx"
# path to the file containing the courses data

## OUTPUT FILES

STUDENT_ALLOCATION: "./output/HSS Registration 2021-22 - Students Allocation.xlsx"
# path where final allocation is stored student wise

COURSE_ALLOCATION: "./output/HSS Registration 2021-22 - Courses Allocation.xlsx"
# path where final allocation is stored course wise

INSIGHTS_PATH: "./insights"
# path to store the insights

## INPUT PARAM

NUM_ITERATIONS: 1000
# number of time to run allocation for better results (1000 iterations take 2 mins approx)
